FROM node:16-alpine as build-step
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH
COPY package.json /app/
COPY yarn.lock /app/
RUN apk add --no-cache git
RUN yarn && yarn install 
COPY . /app

CMD ["yarn", "start"]

# FROM nginx:stable-alpine

# COPY --from=build-step /app/build /usr/share/nginx/html
# COPY deployment/nginx.default.conf /etc/nginx/conf.d/default.conf