"""empty message

Revision ID: 1ef8c0239579
Revises: 
Create Date: 2021-09-24 15:30:36.789945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ef8c0239579'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('organization', sa.Text(), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('confirmation_link_sent_on', sa.DateTime(), nullable=True),
    sa.Column('email_confirmed', sa.Boolean(), nullable=True),
    sa.Column('email_confirmed_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_index('ix_Users_email', table_name='Users')
    op.drop_table('Users')
    op.drop_constraint(None, 'NN_Query', type_='foreignkey')
    op.create_foreign_key(None, 'NN_Query', 'users', ['user_email'], ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'NN_Query', type_='foreignkey')
    op.create_foreign_key(None, 'NN_Query', 'Users', ['user_email'], ['email'])
    op.create_table('Users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=80), nullable=False),
    sa.Column('password', sa.VARCHAR(length=25), nullable=False),
    sa.Column('organization', sa.VARCHAR(length=50), nullable=False),
    sa.Column('registered_on', sa.DATETIME(), nullable=False),
    sa.Column('confirmation_link_sent_on', sa.DATETIME(), nullable=True),
    sa.Column('email_confirmed', sa.BOOLEAN(), nullable=True),
    sa.Column('email_confirmed_on', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_Users_email', 'Users', ['email'], unique=False)
    op.drop_table('users')
    # ### end Alembic commands ###
