from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # op.add_column('experiments', sa.Column('kountry', sa.String(length=100), nullable=True))
    # op.drop_column('experiments', 'countryland')

    op.alter_column('user',
                     column_name = 'username',
                     new_column_name = 'email',
                     existing_type = sa.Text,
                     existing_nullable = False,
                     existing_server_default = 'Greenland')

    # ### end Alembic commands ###